version: '2'

services:
  backend:
    image: pipetop/container-storage
    ports:
      - 8878:8878
    environment:
      - CELERY_BROKER_REDIS_URL=backend-worker-redis.h4s6xj.0001.euw1.cache.amazonaws.com
      - CELERY_RESULTS_REDIS_URL=backend-worker-redis.h4s6xj.0001.euw1.cache.amazonaws.com
      - ELASTICSEARCH_URL=https://search-proto-es-23-hh7x4mw6gx5dgsh27zez5qbrk4.eu-west-1.es.amazonaws.com
      - MYSQL_HOST=proto-backend-storage.cgnfgjir0owe.eu-west-1.rds.amazonaws.com
  worker:
    image: pipetop/container-storage
    environment:
      - C_FORCE_ROOT=1
      - CELERY_BROKER_REDIS_URL=backend-worker-redis.h4s6xj.0001.euw1.cache.amazonaws.com
      - CELERY_RESULTS_REDIS_URL=backend-worker-redis.h4s6xj.0001.euw1.cache.amazonaws.com
      - ELASTICSEARCH_URL=https://search-proto-es-23-hh7x4mw6gx5dgsh27zez5qbrk4.eu-west-1.es.amazonaws.com
      - MYSQL_HOST=proto-backend-storage.cgnfgjir0owe.eu-west-1.rds.amazonaws.com
    command: /app/start_celery_workers.sh
networks:
  default:
    driver: overlay
    ipam:
      driver: default
      config:
        - subnet: 10.0.11.0/24
